# Copyright 2020 Serghei Iakovlev <egrep@protonmail.ch>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: analysis

on:
  pull_request:
    branches:
      - master
      - development
  push:

jobs:
  code_style:
    name: "${{ matrix.project }}: analysis"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - stars

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - name: Get PIP Cache Key
        id: pip-cache
        run: |
          python -c "from pip._internal.locations import USER_CACHE_DIR; \
                  print('::set-output name=dir::' + USER_CACHE_DIR)"

      - name: Setup pip Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        working-directory: ${{ matrix.project }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          sudo apt-get install --no-install-recommends -q -y clang-format

      - name: Run CMake Coding Style Check
        working-directory: ${{ matrix.project }}
        run: |
          cmake-format --version

          cmake-format -i $(find ./cmake -name '*.cmake')
          cmake-format -i $(find . -name CMakeLists.txt)
          git diff --exit-code

      - name: Run C++ Coding Style Check
        if: always()
        working-directory: ${{ matrix.project }}
        run: |
          clang-format --version

          clang-format -i $(find ./src -name '*.[hc]pp')
          clang-format -i $(find ./include -name '*.[hc]pp')
          git diff --exit-code

      - name: Run Cpplint Check
        if: always()
        run: cpplint --counting=detailed --recursive src include
